

services:
  api:
    build: .
    container_name: calculator-api
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
    volumes:
      - .:/app
      - /app/node_modules
    command: node src/app.js
    networks:
      - calculator-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - calculator-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SERVER_ROOT_URL=http://localhost:3001
    depends_on:
      - prometheus
    networks:
      - calculator-network

networks:
  calculator-network:
    driver: bridge
